spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: Svetlana77
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

properties:
  user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
  referrer: http://www.google.com
  sites:
  - url: http://www.playback.ru
    name: Магазин Playback
  - url: http://radiomv.ru
    name: Радио Милицейская волна
  - url: https://ipfran.ru
    name: Институт прикладной физики РАН
  - url: https://dimonvideo.ru
    name: Все для мобильных устройств
  - url: https://nikoartgallery.com
    name: Галерея Никогосяна
  - url: https://et-cetera.ru/mobile
    name: Театр «Et Cetera»
  - url: https//www.lutherancathedral.ru
    name: Собор Петра и Павла
  - url: https://dombulgakova.ru
    name: Булгаковский Дом
  - url: https://www.svetlovka.ru
    name: Центральная городская молодежная библиотека им. М. А. Светлова
  - url: https://volochek.life
    name: Портал города Вышний Волочек